# TPM - base
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# TPM - plugins
set -g @dracula-show-fahrenheit false
set -g @plugin 'dracula/tmux'

# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Numbering of windows and panels
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Status position
set-option -g status-position top

run '~/.tmux/plugins/tpm/tpm'
